### ISSUE TITLE
GCanvas Node，gcanvas build 成功后，运行demo，显示以下错误

### ISSUE THREAD

**Issue by bobhfut** [alibaba/GCanvas#187]
Error: Could not locate the bindings file. Tried:
 → /gcanvas/build/canvas.node
 → /gcanvas/build/Debug/canvas.node
 → /gcanvas/build/Release/canvas.node
 → /gcanvas/out/Debug/canvas.node
 → /gcanvas/Debug/canvas.node
 → /gcanvas/out/Release/canvas.node
 → /gcanvas/Release/canvas.node
 → /gcanvas/build/default/canvas.node
 → /gcanvas/compiled/10.23.0/linux/x64/canvas.node
    at bindings (/gcanvas/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/gcanvas/src/a.js:1:52)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by bobhfut** [comment]
从npm 安装的
