### ISSUE TITLE
System.loadLibrary fails (Trying to write a bridge for NativeScript)

### ISSUE THREAD

**Issue by nerfpops** [alibaba/GCanvas#20]
When initializing GTextureView, it throws:

```
03-23 13:56:47.570 24743 24743 E GTextureViewCallback:  at com.tns.Runtime.callJSMethodNative(Native Method)
03-23 13:56:47.570 24743 24743 E GTextureViewCallback:  at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
03-23 13:56:47.570 24743 24743 E GTextureViewCallback:  at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
03-23 13:56:47.570 24743 24743 E GTextureViewCallback:  at com.tns.Runtime.callJSMethod(Runtime.java:957)
03-23 13:56:47.570 24743 24743 E GTextureViewCallback:  at com.tns.Runtime.callJSMethod(Runtime.java:941)
03-23 13:56:47.570 24743 24743 E GTextureViewCallback:  at com.tns.Runtime.callJSMethod(Runtime.java:933)
```

which doesn't say much, but after a bit of digging I found this in GTextureViewCallback:

```java
static {
	if(!INITIALIZED) {
		try {
			System.loadLibrary("gcanvas");
			System.loadLibrary("freetype");
			GCanvasJNI.setFontFamilies();
			INITIALIZED = true;
		} catch (Throwable var1) {
			GLog.e("GTextureViewCallback", "error when load library", var1);
		}
	}
}
```

So I tried executing `System.loadLibrary("freetype")` which failed:

```
JS: ERROR Error: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.nativescript.test-WSsnJQcOMx_opeWwBYpiIg==/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.test-WSsnJQcOMx_opeWwBYpiIg==/lib/x86, /data/app/org.nativescript.test-WSsnJQcOMx_opeWwBYpiIg==/base.apk!/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libfreetype.so"
```

It's almost the same for `System.loadLibrary("gcanvas")`.

Does anyone know what I'm doing wrong?

Update: I'm assuming it might be because there's no x86/x64 version of freetype and gcanvas specified in Android.mk, but it's kind of hard to test, because an arm-emulator takes forever to boot.

**Comment by nerfpops** [comment]
It was a combination of me not including the aar correctly and a missing x86 build.
