### ISSUE TITLE
Gcanvas与weex sdk 0.19版本不兼容

### ISSUE THREAD

**Issue by chenzefeng09** [alibaba/GCanvas#43]
weex team is releasing a new version(0.19),it makes lots of changes and GCanvas can not work well with this version for now,for example,WXDomObject class was removed in android code.Is there a plan to release a new gcanvas version to fix that?

**Comment by chenzefeng09** [comment]
weex 0.19一些类删除了，与Gcanvas不兼容

**Comment by liushengyi** [comment]
哎，没人管了

**Comment by dourgulf** [comment]
请问这个兼容性修复了吗？

**Comment by liushengyi** [comment]
发现源码中libweexjsc.so在weex新版sdk中不存在了

**Comment by liushengyi** [comment]
与0.19的兼容性可以这样解决：
1 copy  WXGCanvasWeexComponent  GCanvasWeexModule，对应修改下构造方法和引用
   GCanvasJNI中的libweexjsc.so替换成libweexcore.so
2 下载GCanvas源码修改core模块的GCanvasJNI.cpp，将libweexjsc.so替换成libweexcore.so
  重新编译core模块，生成so

**Comment by chenzefeng09** [comment]
@liushengyi 感谢
目前还是crash，报错如下，像是新的weex so库没有实现这个方法

` E/crash: [, , 0]:java.lang.UnsatisfiedLinkError: No implementation found for void com.taobao.gcanvas.GCanvasJNI.registerCallback(java.lang.String, int) (tried Java_com_taobao_gcanvas_GCanvasJNI_registerCallback and Java_com_taobao_gcanvas_GCanvasJNI_registerCallback__Ljava_lang_String_2I)
        at com.taobao.gcanvas.GCanvasJNI.registerCallback(Native Method)
        at com.taobao.gcanvas.GCanvasJNI.registerWXCallNativeFunc(GCanvasJNI.java:123)
        at com.taobao.gcanvas.bridges.weex.WXGCanvasWeexComponent.addGCanvasView(WXGCanvasWeexComponent.java:51)
        at com.taobao.gcanvas.bridges.weex.WXGCanvasWeexComponent.initComponentHostView(WXGCanvasWeexComponent.java:93)
        at com.taobao.gcanvas.bridges.weex.WXGCanvasWeexComponent.initComponentHostView(WXGCanvasWeexComponent.java:31)
        at com.taobao.weex.ui.component.WXComponent.createViewImpl(WXComponent.java:1428)
        at com.taobao.weex.ui.component.WXComponent.createView(WXComponent.java:1422)
        at com.taobao.weex.ui.component.WXVContainer.createChildViewAt(WXVContainer.java:282)
        at com.taobao.weex.ui.flat.WidgetContainer.createChildViewAt(WidgetContainer.java:82)
        at com.taobao.weex.ui.action.GraphicActionAddElement.executeAction(GraphicActionAddElement.java:174)
        at com.taobao.weex.ui.action.BasicGraphicAction.run(BasicGraphicAction.java:68)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)`

**Comment by dourgulf** [comment]
@liushengyi 为什么要“将libweexjsc.so替换成libweexcore.so” ??

**Comment by jwxbond** [comment]
update to new weexsdk 0.28
