### ISSUE TITLE
GCanvas DrawText 设置高质量mHiQuality后 Transform不生效

### ISSUE THREAD

**Issue by captain6541** [alibaba/GCanvas#78]
设置高质量后没有锯齿，但是绘制图表的时候，text的Transform不生效了。

**Comment by Popo19** [comment]
按照官方步骤集成到安卓端，运行报以下错误，能麻烦你看一下是什么原因吗
E/com.weex.app: No implementation found for void com.taobao.gcanvas.GCanvasJNI.registerCallback(java.lang.String, int) (tried Java_com_taobao_gcanvas_GCanvasJNI_registerCallback and Java_com_taobao_gcanvas_GCanvasJNI_registerCallback__Ljava_lang_String_2I)
E/GTextureViewCallback: error when load library
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/base.apk", zip file "/data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_dependencies_apk.apk", zip file "/data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_resources_apk.apk", zip file "/data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_0_apk.apk", zip file "/data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_1_apk.apk", zip file "/data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_2_apk.apk", zip file "/data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_3_apk.apk", zip file "/data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_4_apk.apk", zip file "/data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_5_apk.apk", zip file "/data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_6_apk.apk", zip file "/data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_7_apk.apk", zip file "/data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_8_apk.apk", zip file "/data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/lib/x86, /data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/base.apk!/lib/x86, /data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.weex.app-XvrpnpY4vdR0fk1xS34X9A==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib]]] couldn't find "libgcanvas.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.taobao.gcanvas.surface.GTextureViewCallback.<clinit>(GTextureViewCallback.java:33)
        at com.taobao.gcanvas.surface.GTextureView.init(GTextureView.java:63)
        at com.taobao.gcanvas.surface.GTextureView.<init>(GTextureView.java:21)
        at com.taobao.gcanvas.bridges.weex.GWXTextureView.<init>(GWXTextureView.java:20)
        at com.taobao.gcanvas.bridges.weex.WXGCanvasWeexComponent.addGCanvasView(WXGCanvasWeexComponent.java:42)
        at com.taobao.gcanvas.bridges.weex.WXGCanvasWeexComponent.initComponentHostView(WXGCanvasWeexComponent.java:101)
        at com.taobao.gcanvas.bridges.weex.WXGCanvasWeexComponent.initComponentHostView(WXGCanvasWeexComponent.java:31)
        at com.taobao.weex.ui.component.WXComponent.createViewImpl(WXComponent.java:1002)
        at com.taobao.weex.ui.component.WXComponent.createView(WXComponent.java:994)
        at com.taobao.weex.ui.component.WXVContainer.createChildViewAt(WXVContainer.java:284)
        at com.taobao.weex.ui.flat.WidgetContainer.createChildViewAt(WidgetContainer.java:80)
        at com.taobao.weex.dom.action.AddElementAction.executeRender(AddElementAction.java:109)
        at com.taobao.weex.dom.RenderActionTask.execute(RenderActionTask.java:50)
        at com.taobao.weex.ui.WXRenderManager$1.run(WXRenderManager.java:104)
        at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:49)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
E/GTextureViewCallback:     at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
