### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by pongponglau** [alibaba/GCanvas#80]
I can build the project RNGCanvasSample successfully. When i run it on android, the app is crashed with the following error:

02-14 17:08:11.599 11331-11331/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rngcanvassample, PID: 11331
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at com.taobao.gcanvas.GCanvasJNI.refreshArguments(GCanvasJNI.java:85)
        at com.taobao.gcanvas.surface.GTextureViewCallback.onSurfaceTextureAvailable(GTextureViewCallback.java:75)
        at android.view.TextureView.getHardwareLayer(TextureView.java:390)
        at android.view.TextureView.draw(TextureView.java:339)
        at android.view.View.updateDisplayListIfDirty(View.java:18168)
        at android.view.View.draw(View.java:18946)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4238)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:804)
        at android.view.View.updateDisplayListIfDirty(View.java:18159)
        at android.view.View.draw(View.java:18946)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4238)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:804)
        at android.view.View.draw(View.java:19221)
        at android.view.View.updateDisplayListIfDirty(View.java:18168)
        at android.view.View.draw(View.java:18946)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4238)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18159)
        at android.view.View.draw(View.java:18946)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4238)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18159)
        at android.view.View.draw(View.java:18946)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4238)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18159)
        at android.view.View.draw(View.java:18946)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4238)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.draw(View.java:19221)
        at com.android.internal.policy.DecorView.draw(DecorView.java:791)
        at android.view.View.updateDisplayListIfDirty(View.java:18168)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:685)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:691)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:799)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3053)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2848)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2401)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1434)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6868)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
        at android.view.Choreographer.doCallbacks(Choreographer.java:838)
        at android.view.Choreographer.doFrame(Choreographer.java:769)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

May i ask for your help to fix this?

Thanks a lot

**Comment by pongponglau** [comment]
Do the following logs matter?

02-14 17:34:14.218 12642-12642/? D/ApkSoSource: not allowing consideration of lib/armeabi-v7a/libfb.so: deferring to libdir
    not allowing consideration of lib/armeabi-v7a/libfolly_json.so: deferring to libdir
    not allowing consideration of lib/armeabi-v7a/libfreetype.so: deferring to libdir
    not allowing consideration of lib/armeabi-v7a/libgcanvas.so: deferring to libdir
    not allowing consideration of lib/armeabi-v7a/libglog.so: deferring to libdir
    not allowing consideration of lib/armeabi-v7a/libglog_init.so: deferring to libdir
    not allowing consideration of lib/armeabi-v7a/libgnustl_shared.so: deferring to libdir
    not allowing consideration of lib/armeabi-v7a/libicu_common.so: deferring to libdir
    not allowing consideration of lib/armeabi-v7a/libimagepipeline.so: deferring to libdir
    not allowing consideration of lib/armeabi-v7a/libjsc.so: deferring to libdir
    not allowing consideration of lib/armeabi-v7a/libprivatedata.so: deferring to libdir
    not allowing consideration of lib/armeabi-v7a/libreactnativejni.so: deferring to libdir
    not allowing consideration of lib/armeabi-v7a/libyoga.so: deferring to libdir

**Comment by flyskywhy** [comment]
@pongponglau I once [fix: avoid sometimes `java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.taobao.gcanvas.bridges.rn.GReactTextureView.isReady()' on a null object reference`](https://github.com/flyskywhy/react-native-gcanvas/commit/27a131f) , maybe you can ref to it.

Since Alibaba [feat: delete weex bridge & reactive bridge](https://github.com/alibaba/GCanvas/commit/1bbee40a16c0c5da58698e2892ba33f836eedb70), here comes the [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) npm package.

After months work, [@flyskywhy/react-native-gcanvas](https://github.com/flyskywhy/react-native-gcanvas) runs well on Android and iOS, fix several bugs and add `feat: support drawImage() from require('some.png') on Android, iOS and Web` described in [Changelog.md](https://github.com/flyskywhy/react-native-gcanvas/blob/master/docs/Changelog.md), refactor with the detailed [Example As Usage](https://github.com/flyskywhy/react-native-gcanvas#example-as-usage) in README.md.

With [Performance Test Result](https://github.com/flyskywhy/react-native-gcanvas#performance-test-result), and [Convenient With Browser-like canvas APIs](https://github.com/flyskywhy/react-native-gcanvas#convenient-with-browser-like-canvas-apis) with the easily `<canvas/>` ported example [react-native-particles-bg](https://github.com/flyskywhy/react-native-particles-bg) runs on Android, iOS and Web, `@flyskywhy/react-native-gcanvas` is the best choice for now :yum:
